export interface Product {
  id: string;
  name: string;
  category: string;
  description: string;
  price: number;
  image: string;
  origin: string;
  abv?: string;
  featured?: boolean;
}

export const categories = [
  "All",
  "Whisky",
  "Gin",
  "Vodka",
  "Cognac",
  "Rum",
  "Tequila",
  "Liqueur",
  "Wine & Champagne",
];

export const products: Product[] = [
  {
    id: "chivas-12",
    name: "Chivas Regal 12 Year Old",
    category: "Whisky",
    description: "A luxurious blended Scotch whisky with honey, vanilla, and ripe apple notes. Crafted at the legendary Strathisla distillery since 1786.",
    price: 450,
    image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&h=800&fit=crop",
    origin: "Scotland",
    abv: "40%",
    featured: true,
  },
  {
    id: "chivas-18",
    name: "Chivas Regal 18 Year Old",
    category: "Whisky",
    description: "A rich and complex blended Scotch whisky aged for 18 years. Dark chocolate, dried fruit and elegant floral notes.",
    price: 850,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&h=800&fit=crop",
    origin: "Scotland",
    abv: "40%",
  },
  {
    id: "royal-salute-21",
    name: "Royal Salute 21 Year Old",
    category: "Whisky",
    description: "The pinnacle of blended Scotch whisky. A regal blend aged for a minimum of 21 years with smoky, fruity complexity.",
    price: 2200,
    image: "https://images.unsplash.com/photo-1602081115068-1e4db2e5ee8c?w=600&h=800&fit=crop",
    origin: "Scotland",
    abv: "40%",
  },
  {
    id: "ballantines-finest",
    name: "Ballantine's Finest",
    category: "Whisky",
    description: "A smooth and complex blended Scotch with hints of vanilla, honey and fresh apple. A true Scottish classic.",
    price: 220,
    image: "https://images.unsplash.com/photo-1585975754487-de5a556e1f72?w=600&h=800&fit=crop",
    origin: "Scotland",
    abv: "40%",
  },
  {
    id: "glenlivet-12",
    name: "The Glenlivet 12 Year Old",
    category: "Whisky",
    description: "A single malt whisky with tropical fruit, vanilla and subtle spice. The original Speyside classic.",
    price: 550,
    image: "https://images.unsplash.com/photo-1574783335931-93ade4489e91?w=600&h=800&fit=crop",
    origin: "Scotland",
    abv: "40%",
    featured: true,
  },
  {
    id: "jameson-original",
    name: "Jameson Irish Whiskey",
    category: "Whisky",
    description: "Triple distilled and perfectly smooth. The world's favourite Irish whiskey with notes of vanilla, toasted wood and sweet sherry.",
    price: 320,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&h=800&fit=crop",
    origin: "Ireland",
    abv: "40%",
    featured: true,
  },
  {
    id: "jameson-black-barrel",
    name: "Jameson Black Barrel",
    category: "Whisky",
    description: "Rich and complex with intensified sweetness from double-charred bourbon barrels. Butterscotch, toffee and spice.",
    price: 480,
    image: "https://images.unsplash.com/photo-1598018553943-82da748ff653?w=600&h=800&fit=crop",
    origin: "Ireland",
    abv: "40%",
  },
  {
    id: "malfy-originale",
    name: "Malfy Gin Originale",
    category: "Gin",
    description: "Inspired by the Amalfi Coast lifestyle. Italian crafted gin with juniper and coastal botanicals. La Dolce Vita in a glass.",
    price: 380,
    image: "https://images.unsplash.com/photo-1609951651556-5334e2706168?w=600&h=800&fit=crop",
    origin: "Italy",
    abv: "41%",
    featured: true,
  },
  {
    id: "malfy-limone",
    name: "Malfy Gin Con Limone",
    category: "Gin",
    description: "Infused with Italian Sfusato lemons from the Amalfi Coast. Bright, zesty and perfect for a Mediterranean G&T.",
    price: 420,
    image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=600&h=800&fit=crop",
    origin: "Italy",
    abv: "41%",
  },
  {
    id: "beefeater-london-dry",
    name: "Beefeater London Dry Gin",
    category: "Gin",
    description: "A bold London Dry Gin with a perfectly balanced flavour of juniper and citrus. The quintessential gin since 1863.",
    price: 280,
    image: "https://images.unsplash.com/photo-1607622750671-6cd9a99eabd1?w=600&h=800&fit=crop",
    origin: "England",
    abv: "40%",
  },
  {
    id: "seagrams-gin",
    name: "Seagram's Extra Dry Gin",
    category: "Gin",
    description: "An exceptionally smooth gin with a well-balanced botanical recipe. Clean and versatile for any cocktail.",
    price: 200,
    image: "https://images.unsplash.com/photo-1587223962217-f4fd50f5fbe4?w=600&h=800&fit=crop",
    origin: "USA",
    abv: "40%",
  },
  {
    id: "absolut-original",
    name: "Absolut Vodka",
    category: "Vodka",
    description: "Made from winter wheat and pristine deep well water. One source, one community — Åhus, Sweden since 1879.",
    price: 250,
    image: "https://images.unsplash.com/photo-1613063027689-97b96a19cadf?w=600&h=800&fit=crop",
    origin: "Sweden",
    abv: "40%",
    featured: true,
  },
  {
    id: "absolut-citron",
    name: "Absolut Citron",
    category: "Vodka",
    description: "A vibrant lemon-flavoured vodka with a fresh and zesty character. The original flavoured vodka since 1988.",
    price: 270,
    image: "https://images.unsplash.com/photo-1624797432677-6f803a98acb3?w=600&h=800&fit=crop",
    origin: "Sweden",
    abv: "40%",
  },
  {
    id: "martell-vs",
    name: "Martell VS Single Distillery",
    category: "Cognac",
    description: "From the oldest of the great cognac houses, founded in 1715. Fruity and rounded with notes of plum and grapefruit.",
    price: 520,
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=600&h=800&fit=crop",
    origin: "France",
    abv: "40%",
    featured: true,
  },
  {
    id: "martell-vsop",
    name: "Martell VSOP Aged in Red Barrels",
    category: "Cognac",
    description: "Aged in fine-grained red barrels for an exceptionally smooth and mellow cognac with candied fruit and sandalwood.",
    price: 950,
    image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&h=800&fit=crop",
    origin: "France",
    abv: "40%",
  },
  {
    id: "havana-club-3",
    name: "Havana Club 3 Años",
    category: "Rum",
    description: "Light and fresh Cuban rum aged for 3 years. The authentic base for a perfect Mojito or Daiquiri.",
    price: 280,
    image: "https://images.unsplash.com/photo-1598018553943-82da748ff653?w=600&h=800&fit=crop",
    origin: "Cuba",
    abv: "40%",
  },
  {
    id: "malibu-original",
    name: "Malibu Caribbean Rum",
    category: "Rum",
    description: "Smooth coconut-flavoured rum liqueur. The taste of the Caribbean — tropical, refreshing and endlessly mixable.",
    price: 250,
    image: "https://images.unsplash.com/photo-1587223962217-f4fd50f5fbe4?w=600&h=800&fit=crop",
    origin: "Barbados",
    abv: "21%",
  },
  {
    id: "avion-silver",
    name: "Avión Silver Tequila",
    category: "Tequila",
    description: "Ultra-premium tequila crafted from hand-selected 100% Blue Weber agave. Clean, crisp with a smooth finish.",
    price: 650,
    image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&h=800&fit=crop",
    origin: "Mexico",
    abv: "40%",
  },
  {
    id: "olmeca-altos-plata",
    name: "Olmeca Altos Plata",
    category: "Tequila",
    description: "Handcrafted tequila using traditional tahona process. Fresh agave, citrus and herbal notes.",
    price: 380,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&h=800&fit=crop",
    origin: "Mexico",
    abv: "38%",
  },
  {
    id: "kahlua-original",
    name: "Kahlúa Coffee Liqueur",
    category: "Liqueur",
    description: "Rich coffee liqueur made with 100% Arabica coffee beans and rum. The original Espresso Martini ingredient.",
    price: 350,
    image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=600&h=800&fit=crop",
    origin: "Mexico",
    abv: "20%",
  },
  {
    id: "mumm-cordon-rouge",
    name: "G.H. Mumm Cordon Rouge",
    category: "Wine & Champagne",
    description: "Iconic champagne with the bold red sash. Fresh and vibrant with notes of peach, citrus and a hint of vanilla.",
    price: 750,
    image: "https://images.unsplash.com/photo-1594372365401-3b5ff14eaaed?w=600&h=800&fit=crop",
    origin: "France",
    abv: "12%",
    featured: true,
  },
  {
    id: "campo-viejo-tempranillo",
    name: "Campo Viejo Tempranillo",
    category: "Wine & Champagne",
    description: "Spain's number one wine brand. A vibrant Rioja with ripe berry fruit and subtle oak. Perfect with rich foods.",
    price: 180,
    image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&h=800&fit=crop",
    origin: "Spain",
    abv: "13.5%",
  },
  {
    id: "jacobs-creek-shiraz",
    name: "Jacob's Creek Classic Shiraz",
    category: "Wine & Champagne",
    description: "A rich and full-bodied Australian Shiraz with plum, blackberry and spice. Perfect for any occasion.",
    price: 150,
    image: "https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=600&h=800&fit=crop",
    origin: "Australia",
    abv: "13.5%",
  },
];

export function getProductsByCategory(category: string): Product[] {
  if (category === "All") return products;
  return products.filter((p) => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}
